# Gunakan image base python yang cocok dengan TensorFlow
FROM python:3.9-slim

# Install dependencies untuk TensorFlow
RUN apt-get update && apt-get install -y \
    build-essential \
    libopenblas-dev \
    liblapack-dev \
    libjpeg-dev \
    python3-dev \
    libhdf5-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Buat dan aktifkan virtual environment
WORKDIR /app
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Salin file requirements.txt ke dalam container
COPY ./app/requirements.txt /app/requirements.txt

# Update pip dan install dependencies
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Salin semua file aplikasi
COPY ./app /app

# Jalankan aplikasi menggunakan uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
